name: UbuntuLatestGCC

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: installing dependencies
      run: |
           sudo apt -y update
           sudo apt -y install qt5-default libboost-all-dev libcgal-dev libgmp-dev libqglviewer-dev-qt5 libeigen3-dev
           cd ..
           git clone --recursive https://github.com/libigl/libigl
           git clone --depth=1 --branch=devel https://github.com/cnr-isti-vclab/vcglib.git
           git clone https://github.com/mlivesu/cinolib.git
    - name: compiling examples
      run: |
           export LIBIGL_HOME=$(pwd)/../libigl
           export VCGLIB_HOME=$(pwd)/vcglib
           export CINOLIB_HOME=$(pwd)/cinolib
           cd examples
           qmake examples.pro
           make
      
